version : '3.8'
services:
  ruoyi-redis:
    restart: always
    image: richardgong1987/docker_ruoyi-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server /home/ruoyi/redis/redis.conf
  ruoyi-nginx:
    restart: always
    image: richardgong1987/docker_ruoyi-vue-nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d

  ruoyi-modules-education-admin:
    restart: always
    image: richardgong1987/docker_ruoyi-vue:latest
    ports:
      - "8080:8080"

